language: r
pandoc_version: 2.2.1
dist: trusty
sudo: false

branches:
  only:
    - master

# cache local changes
cache:
  packages: no
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
    
# install the package and dependencies:
# - update all installed packages
# - install package with dependencies
install:
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'install.packages("tinytex")'
  - Rscript -e 'tinytex::install_tinytex()'
  - Rscript -e 'update.packages(ask = FALSE)'
  - Rscript -e 'devtools::install(pkg = ".", dependencies = TRUE)'

# render both output forms of the book
script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"

# deploy book to gh-pages branch
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: _book
  #target-branch: master
  keep-history: true
  allow-empty-commit: false

# send email if any changes
notifications:
  email:
    on_success: change
    on_failure: change
