--- 
title: "Shrinking Characteristics of Precision Matrix Estimators: An Illustration via Regression"
author: "Matt Galloway"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::pdf_book:
    toc_depth: 2
    fig_caption: yes
    includes:
      in_header: preamble.tex
  bookdown::gitbook:
    toc_depth: 2
documentclass: report
bibliography: [lib.bib, packages.bib]
#bibliography: lib.bib
biblio-style: apalike
#geometry: "left=4cm, right=3cm, top=2.5cm, bottom=2.5cm"
#geometry: "left = 1.5in, right = 1in, top = 1in, bottom = 1in"
geometry: "left = 1in, right = 1in, top = 1in, bottom = 1in"
colorlinks: yes
lot: no
lof: no
toc_appendix: yes
fontsize: 11pt
linestretch: 1.5
link-citations: yes
#url: 'https://mgallow.github.io/oral_manuscript/'
github-repo: MGallow/oral_manuscript
description: "This is a working manuscript in preparation for Matt Galloway's master's thesis defense."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, tidy = TRUE, out.width = "90%", fig.align = "center", out.extra = "")

```

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(.packages(), "glasso", "ADMMsigma", "SCPME"), 'packages.bib')

```

